Arithmetics
Edgars01/C-Sharp_Syllabus pull request #1
Opened 2021-11-27 10:59 UTC by Edgars01

2021-11-27 14:32 UTC, ausmoons requested changes

2021-11-27 14:32 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/CalculateArea/Geometry.cs
> +            double area = ground * h * 0.5;
Šeit var uzreiz return, jo area nekur savādāk netiek izmantots

2021-11-27 14:32 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/CalculateArea/Program.cs
> +
Lieka tukša rinda. Jā ir tikai }} bez cita koda, tad nevajag tukšu rindu pa vidu

2021-11-27 14:32 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/CalculateArea/Program.cs
> +        private static void backToMenu()
Metodes ar lielo burtu

2021-11-27 14:32 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/exercise 06/Program.cs
> +	Console.WriteLine();
Te kkas nav ar tabiem

2021-11-27 14:32 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/exercise 08/Program.cs
> +        public static int CalculatePay(double pay, double hours)
Starp metodēm vajag vienu tukšu rindu

2021-11-27 14:32 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/exercise 09/Program.cs
> +                Console.WriteLine("Your weight is optimal.");
Kur būs 18.5 un 25?

2021-11-30 13:51 UTC, Edgars01 commented
Done

2021-12-01 07:45 UTC, ausmoons requested changes
Sakārto tabbingu

2021-12-01 07:45 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/exercise 01/Program.cs
> +        public static bool test(int a, int b)
Ar lielo burtu metode

2021-12-01 07:45 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/exercise 06/Program.cs
> +		static void Main(string[] args)
Te vēl joprojām tab nav sakārtoti.

2021-12-01 07:45 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/exercise 06/Program.cs
> +		static void Main(string[] args)
Te vajag tikai vienu tab, nevis vairāk (pret iepriekšējo rindiņu)

2021-12-01 07:45 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/exercise 06/Program.cs
> +			Console.WriteLine();
Šim arī nebūtu jābūt vienā līnijā ar }

2021-12-01 08:39 UTC, ausmoons approved these changes

2021-12-01 08:41 UTC, merged