Classes and objects
Edgars01/C-Sharp_Syllabus pull request #7
Opened 2021-12-11 14:03 UTC by Edgars01

2022-01-02 12:30 UTC, ausmoons requested changes

2022-01-02 12:30 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Account/Account.cs
> +        public string _userAccountName;
izskatās pēc private

2022-01-02 12:30 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Account/Program.cs
> +        public static void Transfer(Account from, Account to, decimal howMuch)
starp metodēm vajag tukšu rindu

2022-01-02 12:30 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise1/Program.cs
> +        public int changeQuantity(int newAmount)
Metodes ar lielo burtu

2022-01-02 12:30 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/VideoStore/VideoStore.cs
> +            foreach (var t in _store)
ar linq vari atrast vajadzīgo itemu

2022-01-03 21:27 UTC, Edgars01 commented on csharp-basics/exercises/ClassesAndObjects/VideoStore/VideoStore.cs
> +            foreach (var t in _store)
videoStore fix

2022-01-04 13:42 UTC, ausmoons approved these changes

2022-01-04 16:01 UTC, merged